config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :shifts
  resources :users

  resources :schedules do
    resources :enrollments, shallow: true, except: :index
  end

  # Nest enrollments inside schedules
  get 'schedules/:id/enrollments', to: redirect('/schedules/%{id}')

  # Navbar Search - Typeahead feature
  resources :search do
    collection do
      get :global
      get :all # Navbar Search results
    end
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  before_create :generate_ucode

  has_many :enrollments, dependent: :destroy
  has_many :users, through: :enrollments, foreign_key: 'user_id'
  has_many :shifts

  validates :name, presence: true
  validates :ucode, uniqueness: true

  # Background indexing + Only match start of name
  searchkick callbacks: :async, word_start: [:name]

  protected

  def generate_ucode
    char = ('a'..'z').to_a; num = ('1'..'9').to_a
    new_ucode = 5.times.map{ [ *char, *num ].sample }.join
    code_check = Schedule.find_by_ucode(new_ucode)
    if !code_check
      self.ucode = new_ucode
      return
    else 
      while code_check != nil
        new_ucode = 5.times.map{ [ *char, *num ].sample }.join
        code_check = Schedule.find_by_ucode(new_ucode)
      end
      self.ucode = new_ucode
      return
    end
  end

  #
  # Search a user by Schedule name
  #
  def self.search_by_name(keyword)
    # Nil check and make keyword case insensitive
    return nil unless keyword
    where("name = ?", "%#{keyword}%")
  end # search_by_name
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  def show
    @enrollment = @schedule.enrollments.new
    @shifts = @schedule.shifts
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  def create
    @schedule = Schedule.new(schedule_params)

    if @schedule.save
      redirect_to @schedule, notice: 'Schedule was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /schedules/1
  def update
    if @schedule.update(schedule_params)
      redirect_to @schedule, notice: 'Schedule was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /schedules/1
  def destroy
    @schedule.destroy
    redirect_to schedules_url, notice: 'Schedule was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def schedule_params
      params.require(:schedule).permit(:name, :ucode)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :schedule_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.name %></td>
        <td><%= schedule.ucode %></td>
        <td><%= link_to 'Show Users', schedule_path(schedule) %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Home", root_path %>
<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<h1><%= @schedule.name %></h1>
<p>
  <strong>Name:</strong>
  <%= @schedule.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @schedule.ucode %>
</p>

<br />
<br />
<br />
<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

<div class="pad-top-20">
  <h1>Shifts for <%= @schedule.name %></h1>

  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Schedule</th>
      <th>Assigned To</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Duration</th>
      <th>Repeat</th>
      <th>Repeat every</th>
      <th>Repeat every unit</th>
      <th>Repeat end date</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @shifts.each do |shift| %>
        <tr>
          <td><%= shift.name %></td>
          <td><%= Schedule.find(shift.schedule_id).name %></td>
          <td><%= User.find(shift.user_id).full_name %></td>
          <td><%= shift.start_time %></td>
          <td><%= shift.end_time %></td>
          <td><%= shift.duration %></td>
          <td><%= shift.repeat %></td>
          <td><%= shift.repeat_every %></td>
          <td><%= shift.repeat_every_unit %></td>
          <td><%= shift.repeat_end_date %></td>
          <td><%= link_to 'Show', shift %></td>
          <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
          <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Shift', new_shift_path %>

</div>
</div>

<p id="notice"><%= notice %></p>

<p>
<strong>Name:</strong>
<%= @schedule.name %>
</p>

<p>
<strong>Code:</strong>
<%= @schedule.ucode %>
</p>

<h4>Users in the <%= @schedule.name %></h4>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedule.enrollments.each do |enrollment| %>
      <tr>
        <% if !enrollment.new_record? %>
          <td><%= enrollment.user.first_name %> <%= enrollment.user.last_name %></td>
          <td><%= enrollment.user.email %><td>
          <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<h4>Add User</h4>
<%= render 'enrollments/form'%>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>