config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :shifts
  resources :users

  resources :schedules do
    resources :enrollments, shallow: true, except: :index
  end

  # Nest enrollments inside schedules
  get 'schedules/:id/enrollments', to: redirect('/schedules/%{id}')

  # Navbar Search - Typeahead feature
  resources :search do
    collection do
      get :global
      get :all # Navbar Search results
    end
  end

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :schedule
  validates :user_id, uniqueness: {scope: :schedule_id}
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments/1
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  def create
    @enrollment = Enrollment.new(enrollment_params)
    # verify the schedule exists
    schedule_id = Schedule.find(params[:schedule_id])
    user =  User.find_by! email: enrollment_params[:user_id]
    raise ArgumentError, "Schedule ID #{params[:schedule_id]} not found." unless schedule_id
    @enrollment.schedule_id = Schedule.find(params[:schedule_id]).id
    @enrollment.user_id = user.id
    
    if @enrollment.save
      redirect_to @enrollment.schedule, notice: "#{@enrollment.user.full_name} added to #{@enrollment.schedule.name}"
    else
      @schedule = @enrollment.schedule
      @shifts = @schedule.shifts
      @enrollment.user_id = ""
      render "schedules/show"
    end
  end

  # DELETE /enrollments/1
  def destroy
    @enrollment.destroy
    redirect_to @enrollment.schedule, notice: "#{@enrollment.user.full_name} removed from #{@enrollment.schedule.name}"    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def enrollment_params
      params.require(:enrollment).permit(:user_id, :schedule_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for([@schedule, @enrollment], local: true) do |form| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_id, placeholder: 'email' %>
  </div>

  <div class="actions">
    <%= form.submit "Add to Schedule" %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Schedules User</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.user.email %> </td>
        <td> <%= enrollment.schedule.name %> </td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Home", :home_index %>
<%= link_to 'New Enrollment', new_schedule_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New Schedules User</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>