config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :shifts
  resources :users

  resources :schedules do
    resources :enrollments, shallow: true, except: :index
  end

  # Nest enrollments inside schedules
  get 'schedules/:id/enrollments', to: redirect('/schedules/%{id}')

  # Navbar Search - Typeahead feature
  resources :search do
    collection do
      get :global
      get :all # Navbar Search results
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Zeiter</title>

  <%= csrf_meta_tags %>

  <!-- Load Assets -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav id="navbar" class="navbar navbar-expand-lg navbar-light" style="background-color:;">
    <span id="logo" class="pad-right-20">
      <%= link_to "Zeiter", root_path %>
    </span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Schedules", schedules_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Shifts", shifts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", '#', class: 'nav-link' %>
        </li>
      </ul>

      <!-- User Search -->
      <% if user_signed_in? %>
        <div>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item">
              <span class="navbar-text">Hello, <strong><%= current_user.email.split('@').first %></strong>!</span>
            </li>
            <li class="nav-item">
              <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item pad-right-20">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          </ul>
        </div>

        <!-- Global Search -->
        <% if user_signed_in? %>
            <%= form_tag(all_search_index_path, method: 'get', class: 'form-inline') do %>
                <%= text_field_tag(:query,
                                   params[:query],
                                   placeholder:    'Search User or Shift',
                                   class:          'form-control form-control-sm',
                                   id:             'searchTypeahead',
                                   autocomplete:   :off,
                                   autocorrect:    :off,
                                   autocapitalize: :off) %>
                <%= submit_tag('', name: nil, class: 'hidden', id: 'searchBtn') %>
            <% end %>
        <% end %>

      <% else %>

            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %>
              </li>
              <li class="nav-item pad-right-20">
                <%= link_to "Login", new_user_session_path, :class => 'nav-link' %>
              </li>
            </ul>

        <% end %>
    </div>
  </nav>

  <% if notice %>
      <p class="notice"><%= notice %></p>
  <% end %>

  <% if alert %>
      <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>

  </body>
</html>